"use client";

import { useState } from "react";
import { BookOpen, ChevronDown, HelpCircle, Layers, Clock, TrendingUp, Sparkles, ShieldAlert } from "lucide-react";

interface EducationItem {
  id: string;
  title: string;
  subtitle: string;
  icon: any;
  content: React.ReactNode;
}

export default function StockEducationSection() {
  const [openAccordion, setOpenAccordion] = useState<string | null>("pe-ratio");

  const toggleAccordion = (id: string) => {
    setOpenAccordion((prev) => (prev === id ? null : id));
  };

  const educationItems: EducationItem[] = [
    {
      id: "pe-ratio",
      title: "Price-to-Earnings (P/E) Ratio Explained",
      subtitle: "Valuation Benchmark for Indian Equities",
      icon: BookOpen,
      content: (
        <div className="space-y-2 text-xs leading-relaxed text-slate-300">
          <p>
            The <strong>Price-to-Earnings (P/E) ratio</strong> measures a company&apos;s current share price relative to its per-share earnings. It shows how much investors are willing to pay for every ₹1 of profit generated by the firm.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-2">
            <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-3">
              <span className="font-bold text-emerald-400 block mb-1">Low P/E (&lt; 15-20)</span>
              <span>May indicate an undervalued stock or a mature value enterprise with stable cash flows (e.g. PSUs, Banking blue-chips).</span>
            </div>
            <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-3">
              <span className="font-bold text-amber-400 block mb-1">High P/E (&gt; 35-50+)</span>
              <span>Reflects high growth expectations or premium market sentiment (e.g. IT leaders, FMCG monopolies).</span>
            </div>
          </div>
        </div>
      ),
    },
    {
      id: "market-cap",
      title: "Market Capitalization Tiers (SEBI Rules)",
      subtitle: "Large-Cap, Mid-Cap, & Small-Cap Criteria",
      icon: Layers,
      content: (
        <div className="space-y-2 text-xs leading-relaxed text-slate-300">
          <p>
            In Indian equity markets, the <strong>Securities and Exchange Board of India (SEBI)</strong> categorizes listed companies based on their total market capitalization ranking on the NSE/BSE exchanges:
          </p>
          <ul className="space-y-2 pt-1">
            <li className="flex items-start gap-2">
              <span className="rounded bg-emerald-500/20 px-2 py-0.5 text-[10px] font-extrabold text-emerald-400 shrink-0">Large-Cap</span>
              <span><strong>Top 100 Companies</strong> (&gt; ₹20,000+ Crore Market Cap). High liquidity, stable dividend payouts, lower volatility (e.g. Reliance, TCS, HDFC Bank).</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="rounded bg-indigo-500/20 px-2 py-0.5 text-[10px] font-extrabold text-indigo-400 shrink-0">Mid-Cap</span>
              <span><strong>101st to 250th Companies</strong> (₹5,000 to ₹20,000 Crore Market Cap). High growth potential with moderate market risk.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="rounded bg-amber-500/20 px-2 py-0.5 text-[10px] font-extrabold text-amber-400 shrink-0">Small-Cap</span>
              <span><strong>251st Rank Onwards</strong> (&lt; ₹5,000 Crore Market Cap). Early-stage growth firms with higher volatility and higher potential returns.</span>
            </li>
          </ul>
        </div>
      ),
    },
    {
      id: "delay-disclosure",
      title: "Why is Stock Data 15 Minutes Delayed?",
      subtitle: "Transparent Licensing Rules & Compliance",
      icon: Clock,
      content: (
        <div className="space-y-2 text-xs leading-relaxed text-slate-300">
          <p>
            Per standard <strong>SEBI and Stock Exchange (NSE/BSE)</strong> market data distribution policies, free public market feeds are published with a 15-minute operational delay.
          </p>
          <div className="rounded-xl border border-indigo-500/20 bg-indigo-500/5 p-3 flex items-start gap-2 mt-2">
            <ShieldAlert className="h-4 w-4 text-indigo-400 shrink-0 mt-0.5" />
            <span>
              This disclosure ensures transparency while providing non-commercial investors with free institutional-grade stock intelligence, daily highs/lows, and fundamental valuation metrics without requiring costly broker subscriptions.
            </span>
          </div>
        </div>
      ),
    },
    {
      id: "market-trends",
      title: "Equity Market Dynamics & Interest Rates",
      subtitle: "How Macro Interest Rates & Inflation Impact Stock Valuations",
      icon: TrendingUp,
      content: (
        <div className="space-y-2 text-xs leading-relaxed text-slate-300">
          <p>
            Equity prices do not move in isolation. They react dynamically to macroeconomic variables governed by the <strong>Reserve Bank of India (RBI)</strong> and global central banks:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-2">
            <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3">
              <span className="font-bold text-white block mb-1">Interest Rate Hikes</span>
              <span>Increase corporate borrowing costs, compressing profit margins and compressing growth stock P/E multiples.</span>
            </div>
            <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-3">
              <span className="font-bold text-emerald-400 block mb-1">DII &amp; FII Flows</span>
              <span>Domestic Institutional Investors (DIIs) and Foreign Institutional Investors (FIIs) drive market liquidity and valuation multiples.</span>
            </div>
          </div>
        </div>
      ),
    },
  ];

  return (
    <section className="rounded-3xl border border-emerald-500/20 bg-slate-900/40 p-6 sm:p-8 backdrop-blur-xl space-y-6">
      {/* Section Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800/80 pb-5">
        <div>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-400">
            <Sparkles className="h-3 w-3" />
            Financial Literacy &amp; Educational Knowledge Base
          </span>
          <h2 className="mt-2 text-xl font-black text-white sm:text-2xl">
            Understanding Equity Metrics &amp; Market Dynamics
          </h2>
          <p className="mt-1 text-xs text-slate-400">
            Key concepts to evaluate Indian stock valuations, market caps, and macroeconomic indicators.
          </p>
        </div>
      </div>

      {/* Accordion Cards Grid */}
      <div className="space-y-3">
        {educationItems.map((item) => {
          const Icon = item.icon;
          const isOpen = openAccordion === item.id;

          return (
            <div
              key={item.id}
              className={`overflow-hidden rounded-2xl border transition-all duration-300 ${
                isOpen
                  ? "border-emerald-500/40 bg-slate-900/90 shadow-lg shadow-emerald-950/20"
                  : "border-slate-800/80 bg-slate-900/40 hover:border-slate-700 hover:bg-slate-900/60"
              }`}
            >
              <button
                type="button"
                onClick={() => toggleAccordion(item.id)}
                className="flex w-full items-center justify-between p-4 sm:p-5 text-left focus:outline-none"
              >
                <div className="flex items-center gap-3">
                  <div
                    className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border transition-colors ${
                      isOpen
                        ? "border-emerald-500/40 bg-emerald-500/15 text-emerald-400"
                        : "border-slate-800 bg-slate-800/60 text-slate-400"
                    }`}
                  >
                    <Icon className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-white sm:text-base">{item.title}</h3>
                    <p className="text-xs text-slate-400">{item.subtitle}</p>
                  </div>
                </div>
                <ChevronDown
                  className={`h-5 w-5 text-slate-400 transition-transform duration-300 ${
                    isOpen ? "rotate-180 text-emerald-400" : ""
                  }`}
                />
              </button>

              {isOpen && (
                <div className="border-t border-slate-800/80 px-5 py-4 bg-slate-950/40 animate-fadeIn">
                  {item.content}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}
